// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrabajoFinalDyAW.Models;

public partial class Merchandise
{
    public Guid MerchandiseId { get; set; }

    public string MerchandiseName { get; set; }

    public string MerchandiseDescription { get; set; }

    public string MerchandiseBarcode { get; set; }

    public int MerchandiseStock { get; set; }
}