// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrabajoFinalDyAW.Models;

public partial class Permissionclaim
{
    public string PermissionclaimName { get; set; }

    public virtual ICollection<Userpermisssionclaim> Userpermisssionclaim { get; set; } = new List<Userpermisssionclaim>();
}