// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrabajoFinalDyAW.Models;

public partial class Refreshtoken
{
    public Guid RefreshtokenId { get; set; }

    public string RefreshtokenValue { get; set; }

    public DateTime RefreshtokenExpire { get; set; }

    public Guid UserId { get; set; }

    public virtual User User { get; set; }
}