// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrabajoFinalDyAW.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string UserUsername { get; set; }

    public string UserPassword { get; set; }

    public virtual ICollection<Refreshtoken> Refreshtoken { get; set; } = new List<Refreshtoken>();

    public virtual ICollection<Userpermisssionclaim> Userpermisssionclaim { get; set; } = new List<Userpermisssionclaim>();
}